FROM ubuntu:xenial
RUN apt-get update
RUN apt-get install -y cron
RUN apt-get install -y curl
RUN apt-get install -y jq
WORKDIR /opt/chimera/bin
RUN curl https://devops-command-line-workshop.s3.eu-west-2.amazonaws.com/cliapp --output cliapp
RUN chmod +x cliapp
COPY ./run.sh ./run.sh
RUN chmod +x ./run.sh
# The data folder should be shared with the webapp
ENV DATA_FOLDER=/opt/chimera/data
RUN mkdir /var/log/chimera
RUN touch /var/log/cron.log
ENTRYPOINT ["./run.sh"]
